### ISSUE TITLE
Auto-focus the input box when opening a run prompt

### ISSUE THREAD

**Issue by wilomgfx** [guitarxhero/win98sm#1]
would rate 10/10 if you add this.

**Comment by dd86k** [comment]
I would too.

It's obviously already planned, but I still haven't figured a way.

**Comment by wilomgfx** [comment]
Well you probably already have the element, just .focus() on it ?

**Comment by dd86k** [comment]
The program with that is upon the creation of the node element, if you focus on it and add it to the environment, it _will not_ focus, because **it has been created before displaying**. Thus I've been searching for an event of the sort.

**Comment by dd86k** [comment]
The `autofocus` property fixes this.

**Comment by dd86k** [comment]
...Only for the first instance.

**Comment by dd86k** [comment]
Fixed with shame (a `setTimeout`).
